apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: "llmserving"
spec:
  predictor:
    containers:
    - image: leyao/llmserving:v0.3
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: "90Gi"
          cpu: "10"
        limits:
          memory: "90Gi"
          cpu: "10"
      
