FROM python:3.10-slim

WORKDIR /workspace

COPY requirements.txt ./

RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

RUN pip install intel-extension-for-pytorch oneccl_bind_pt --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/cpu/us/

RUN pip install --no-cache-dir -r ./requirements.txt

COPY llama-2-7b-chat-hf ./llama-2-7b-chat-hf

COPY llm-amx.py ./llm.py

CMD ["python", "llm.py"]
